name: Frontend PullRequest Tests
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on:
  push:
    paths:
      - 'packages/frontend/**'
  pull_request:
    paths:
      - 'packages/frontend/**'
defaults:
  run:
    working-directory: ./packages/frontend
jobs:
  checks:
    name: Linters
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'
          cache: 'yarn'
          cache-dependency-path: packages/frontend/yarn.lock
      - name: Install dependencies
        run: yarn install --immutable
      - name: Check types
        run: yarn run types
      - name: Linter
        run: yarn run lint:check
      - name: Formatter
        run: yarn run prettier:check
      - name: Test build
        run: yarn run build